'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class avisos
    Public Property id As Long
    Public Property cliente As Nullable(Of Long)
    Public Property fechaParaEnviar As Nullable(Of Date)
    Public Property hora As Nullable(Of System.TimeSpan)
    Public Property notificacionEmail As Nullable(Of Boolean)
    Public Property notificacionSms As Nullable(Of Boolean)
    Public Property notificacionApp As Nullable(Of Boolean)
    Public Property mensaje As String
    Public Property fechaCreacion As Nullable(Of Date)
    Public Property enviadaNotificacion As Nullable(Of Boolean)
    Public Property fechaEnviadaNotificacion As Nullable(Of Date)
    Public Property eliminado As Nullable(Of Boolean)
    Public Property fechaEliminado As Nullable(Of Date)
    Public Property emailFarmacia As String
    Public Property emailCliente As String
    Public Property telefonoCliente As String
    Public Property nombreCliente As String

End Class
