'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class botplus
    Public Property cod_barras As String
    Public Property cod_nacional As Long
    Public Property nombre As String
    Public Property grupo_terapeutico As String
    Public Property cod_laboratorio As String
    Public Property laboratorio As String

End Class
