'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cab_pedidos
    Public Property pedido As Integer
    Public Property fecha As Date
    Public Property hora As System.TimeSpan
    Public Property cliente As Integer
    Public Property impreso As Nullable(Of Boolean)
    Public Property enviado As Nullable(Of Boolean)
    Public Property facturado As Nullable(Of Boolean)
    Public Property albaran As Nullable(Of Boolean)
    Public Property cobrado As Nullable(Of Boolean)
    Public Property fechaEnviado As Nullable(Of Date)
    Public Property tienda As String
    Public Property totalBase As Nullable(Of Single)
    Public Property totalIva As Nullable(Of Single)
    Public Property totalVenta As Nullable(Of Single)
    Public Property totalPortesSinIva As Nullable(Of Single)
    Public Property totalPortes As Nullable(Of Single)
    Public Property tipoPago As String
    Public Property referenciaPago As String
    Public Property estadoPrestashop As String
    Public Property idOrderPrestashop As Nullable(Of Integer)
    Public Property eliminado As Nullable(Of Boolean)
    Public Property fechaEliminado As Nullable(Of Date)
    Public Property procesado As Nullable(Of Long)
    Public Property fechaProcesado As Nullable(Of Date)

End Class
