'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cabinas
    Public Property id As Long
    Public Property fecha As Nullable(Of Date)
    Public Property idTrabajador As Nullable(Of Long)
    Public Property idCliente As Nullable(Of Long)
    Public Property habitoAgua As String
    Public Property habitoFuma As String
    Public Property habitoDeporte As String
    Public Property habitoSuenyo As String
    Public Property habitoMedicamentos As String
    Public Property habitoOtros As String
    Public Property pielTipo As String
    Public Property pielTextura As String
    Public Property pielPoro As String
    Public Property pielFirmeza As String
    Public Property pielExpresion As String
    Public Property pielManchas As String
    Public Property pielAltVasc As String
    Public Property pielTez As String
    Public Property pielHidratacion As String
    Public Property pielSensible As String
    Public Property fototipo As String
    Public Property contornoOjos As String
    Public Property prodRecLimpiezaM As String
    Public Property prodRecLimpiezaN As String
    Public Property prodRecOjosM As String
    Public Property prodRecOjosN As String
    Public Property prodRecSerumM As String
    Public Property prodRecSerumN As String
    Public Property prodRecCremaM As String
    Public Property prodRecCremaN As String
    Public Property prodRecProtectorM As String
    Public Property prodRecProtectorN As String
    Public Property prodRecMaquillajeM As String
    Public Property prodRecMaquillajeN As String
    Public Property prodRecOral As String

End Class
