'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class canjeo_puntos
    Public Property id As Long
    Public Property fecha As Nullable(Of Date)
    Public Property dniCliente As String
    Public Property numeroTicket As Nullable(Of Integer)
    Public Property puntosAcumulados As Nullable(Of Single)
    Public Property puntosCanjear As Nullable(Of Single)

End Class
