'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class categoriasps
    Public Property id As Decimal
    Public Property nombre As String
    Public Property padreId As Nullable(Of Long)
    Public Property tieneHijos As Nullable(Of Boolean)
    Public Property prestashopId As Nullable(Of Integer)
    Public Property cargadoPS As Nullable(Of Boolean)
    Public Property eliminado As Nullable(Of Boolean)
    Public Property fechaEliminado As Nullable(Of Date)

End Class
