'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ci_sessions
    Public Property session_id As String
    Public Property ip_address As String
    Public Property user_agent As String
    Public Property last_activity As Long
    Public Property user_data As String
    Public Property progreso As String
    Public Property mensaje As String

End Class
