'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class citas
    Public Property cod As Long
    Public Property cod_curso As Long
    Public Property cod_horario_curso As Long
    Public Property nombre As String
    Public Property telefono As String
    Public Property fecha As Integer
    Public Property impreso As String
    Public Property terminal As String

End Class
