'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class clientesps
    Public Property cliente As Long
    Public Property nombre As String
    Public Property apellidos As String
    Public Property nif As String
    Public Property direccion As String
    Public Property poblacion As String
    Public Property cp As String
    Public Property provincia As String
    Public Property telefono1 As String
    Public Property telefono2 As String
    Public Property movil As String
    Public Property fax As String
    Public Property email As String
    Public Property personaContacto As String
    Public Property recargoEquivalencia As Nullable(Of Boolean)
    Public Property observaciones As String
    Public Property dto As Nullable(Of Integer)
    Public Property regimenFiscal As String
    Public Property fechaAlta As Nullable(Of Date)
    Public Property usuario As String
    Public Property clave As String
    Public Property clave_fedicom As String
    Public Property prestashopCustomerIdPS As Nullable(Of Integer)
    Public Property prestashopAddressIdPS As Nullable(Of Integer)
    Public Property cargadoPS As Nullable(Of Boolean)
    Public Property fechaCargadoPS As Nullable(Of Date)
    Public Property fedicom As Nullable(Of Boolean)
    Public Property prestashop As Nullable(Of Boolean)
    Public Property eliminado As Nullable(Of Boolean)
    Public Property fechaEliminado As Nullable(Of Date)
    Public Property tipoCliente As String

End Class
