'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class clientes_copy
    Public Property cod As Long
    Public Property tarjeta_tra As String
    Public Property dni_tra As String
    Public Property nombre_tra As String
    Public Property tarjeta As String
    Public Property dni As String
    Public Property nombre As String
    Public Property apellidos As String
    Public Property telefono As String
    Public Property direccion As String
    Public Property movil As String
    Public Property observaciones As String
    Public Property email As String
    Public Property puntos As Decimal
    Public Property fecha_nacimiento As Long
    Public Property sexo As String
    Public Property fechaParto As Nullable(Of Date)
    Public Property tipo As String
    Public Property facebook As String
    Public Property maquillaje As String
    Public Property fumar As String
    Public Property piel As String
    Public Property higiene_corporal As String
    Public Property higiene_bucal As String
    Public Property higiene_dental As String
    Public Property homeopatia As String
    Public Property cosmetica As String
    Public Property nutricion_infantil As String
    Public Property infantil As String
    Public Property nutricionydietetica As String
    Public Property dermofarmacia As String
    Public Property cuidado_capilar As String
    Public Property control_peso As String
    Public Property herboristeria As String
    Public Property diabetes As String
    Public Property hipertension As String
    Public Property colesterol As String
    Public Property cuidado_pies As String
    Public Property nivel As Integer
    Public Property nivel_virtual As Integer
    Public Property dia_alta As Date
    Public Property fechaAlta As Nullable(Of Date)
    Public Property baja As Nullable(Of Boolean)
    Public Property twitter As String
    Public Property seguridad_social As String
    Public Property estado_civil As String
    Public Property hijos As Integer
    Public Property hijo1 As String
    Public Property fecha1 As Long
    Public Property hijo2 As String
    Public Property fecha2 As Long
    Public Property hijo3 As String
    Public Property fecha3 As Long
    Public Property hijo4 As String
    Public Property fecha4 As Long
    Public Property hijo5 As String
    Public Property fecha5 As Long
    Public Property dependiente As String
    Public Property frecuencia As String
    Public Property medicamentos As String
    Public Property todo As String
    Public Property faltan As String
    Public Property farmacia_habitual As String
    Public Property habitual As String
    Public Property rostro As String
    Public Property pies As String
    Public Property manos As String
    Public Property cabellos As String
    Public Property dientes As String
    Public Property piel2 As String
    Public Property peso As String
    Public Property otros As String
    Public Property medico As String
    Public Property otros2 As String
    Public Property medico2 As String
    Public Property actividad_fisica As String
    Public Property deporte As String
    Public Property analitica As String
    Public Property alimentacion As String
    Public Property anteriores As String
    Public Property maquillaje2 As String
    Public Property dermocosmetica As String
    Public Property higiene_corporal2 As String
    Public Property higiene_bucal2 As String
    Public Property infantil2 As String
    Public Property higiene_capilar As String
    Public Property dietetica As String
    Public Property productos_naturales As String
    Public Property ortopedia As String
    Public Property optica As String
    Public Property incontinencia As String
    Public Property herboristeria2 As String
    Public Property control_diabetes As String
    Public Property dermocosmetica2 As String
    Public Property consejos_dieteticos As String
    Public Property dietas_personalizadas As String
    Public Property colesterol2 As String
    Public Property complementos_nutricionales As String
    Public Property cuidado_vista As String
    Public Property homeopatia2 As String
    Public Property infantil3 As String
    Public Property embarazo As String
    Public Property deportes As String
    Public Property intolerancias_alimentarias As String
    Public Property fitoterapia As String
    Public Property trastornos_alimentarios As String
    Public Property psicologia As String
    Public Property salud_sexual As String
    Public Property alergias As String
    Public Property problemas_circulatorios As String
    Public Property ninguno As String
    Public Property otros3 As String
    Public Property correo As String
    Public Property email2 As String
    Public Property sms As String
    Public Property charlas_formativas As String
    Public Property en_farmacia As String
    Public Property dejar_fumar As String
    Public Property cigarrillos_dia As Integer
    Public Property ayudas_moviles As String
    Public Property tieneMascota As String
    Public Property practicaDeporte As String
    Public Property dieteticaNutricion As String
    Public Property productosNaturales As String
    Public Property app As Nullable(Of Boolean)
    Public Property whatsapp As Nullable(Of Boolean)
    Public Property lopd As Nullable(Of Boolean)
    Public Property publicidad As Nullable(Of Boolean)

End Class
