'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class compras
    Public Property cod As Long
    Public Property dni As String
    Public Property cod_barras As String
    Public Property cod_nacional As Long
    Public Property medicamento As String
    Public Property familia As String
    Public Property fecha As Long
    Public Property hora As Integer
    Public Property precio As Single
    Public Property dni_tra As String
    Public Property nombre_tra As String
    Public Property puntos As Decimal
    Public Property idventa As Nullable(Of Long)
    Public Property idlinea As Nullable(Of Long)

End Class
