'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class consultas_sql
    Public Property id As Decimal
    Public Property fechaModificacion As Nullable(Of Date)
    Public Property nombre As String
    Public Property sql As String
    Public Property observaciones As String

End Class
