'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class controles_post_tab
    Public Property id As Long
    Public Property idCliente As Nullable(Of Long)
    Public Property tipo As String
    Public Property fecha As Nullable(Of Date)
    Public Property fumadoDesdeDiaD As String
    Public Property cuantosCigDesdeDiaD As String
    Public Property cuantosCigAlDia As String
    Public Property cooximetria As String
    Public Property valorCooximetria As String
    Public Property haTomadoFarmaco As String
    Public Property valorHaTomadoFarmaco As String
    Public Property efAdvNinguno As String
    Public Property efAdIrritacionCutanea As String
    Public Property efAdPicor As String
    Public Property efAdQuemazon As String
    Public Property efAdMialgias As String
    Public Property efAdInsomnio As String
    Public Property efAdSomnolencia As String
    Public Property efAdCefaleas As String
    Public Property efAdConfusion As String
    Public Property efAdNauseas As String
    Public Property efAdVomitos As String
    Public Property efAdMareo As String
    Public Property efAdPalpitaciones As String
    Public Property efAdOtros As String
    Public Property retiraFarmaco As String
    Public Property modificaDosis As String
    Public Property nuevaDosis As Nullable(Of Integer)
    Public Property informacion As String
    Public Property proximaCita As Nullable(Of Date)
    Public Property observaciones As String
    Public Property idTrabajador As Nullable(Of Long)
    Public Property fechaTrabajador As Nullable(Of Date)

End Class
