'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class control_consejos
    Public Property cod As Long
    Public Property tipoConsejo As Nullable(Of Long)
    Public Property consejo As String
    Public Property fecha As Nullable(Of Date)

End Class
