'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class copia_medicamentos
    Public Property cod_barras As String
    Public Property cod_nacional As String
    Public Property nombre As String
    Public Property familia As String
    Public Property precio As Single
    Public Property descripcion As String

End Class
