'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class copia_premios
    Public Property dni As String
    Public Property nombre As String
    Public Property apellidos As String
    Public Property numero_regalos As Single
    Public Property coste_regalos As Single
    Public Property puntos_gastados As Single

End Class
