'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class curso
    Public Property cod As Long
    Public Property fecha As String
    Public Property curso1 As String
    Public Property fecha_inicio As Integer
    Public Property fecha_fin As Integer
    Public Property activo As String
    Public Property orden As Integer
    Public Property email As String
    Public Property externo As String
    Public Property compartido As Integer
    Public Property tiempo As Integer
    Public Property control As Long

End Class
