'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class dar_regalo
    Public Property cod As Long
    Public Property dni As String
    Public Property numticket As String
    Public Property cod_barras As String
    Public Property regalo As String
    Public Property precio As Single
    Public Property fecha As Long
    Public Property puntos As Single
    Public Property dni_tra As String
    Public Property nombre_tra As String

End Class
