'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class dashboard
    Public Property id As Decimal
    Public Property boton As String
    Public Property boton_padre As Nullable(Of Long)
    Public Property activo As Nullable(Of Boolean)
    Public Property grupo As String

End Class
