'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class dbdisponibles
    Public Property id As Long
    Public Property nombre As String
    Public Property disponible As Nullable(Of Boolean)
    Public Property [alias] As String
    Public Property orden As Nullable(Of SByte)

End Class
