'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class dietassrdosnutricion
    Public Property id As Long
    Public Property idHojaRdosNutricion As Nullable(Of Long)
    Public Property idPasoDietasRdosNutricion As Nullable(Of Long)
    Public Property manyana As String
    Public Property noche As String
    Public Property ejercicios As String

End Class
