'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class encuesta
    Public Property cod As Long
    Public Property nombre As String
    Public Property nr1 As Integer
    Public Property respuesta1 As String
    Public Property nr2 As Integer
    Public Property respuesta2 As String
    Public Property nr3 As Integer
    Public Property respuesta3 As String
    Public Property fecha As Integer
    Public Property activo As String

End Class
