'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class entregas_clientes
    Public Property cod As Long
    Public Property idventa As Long
    Public Property idnlinea As Long
    Public Property codigo As String
    Public Property descripcion As String
    Public Property cantidad As Integer
    Public Property precio As Decimal
    Public Property tipo As String
    Public Property fecha As Integer
    Public Property dni As String
    Public Property hora As Date
    Public Property puesto As String
    Public Property trabajador As String
    Public Property fechaEntrega As Nullable(Of Date)
    Public Property pvp As Nullable(Of Single)

End Class
