'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class estadisticas
    Public Property id As Decimal
    Public Property fecha As Nullable(Of Date)
    Public Property campania As String
    Public Property titulo As String
    Public Property mensaje As String
    Public Property imagen As String
    Public Property clientes As Nullable(Of Long)
    Public Property tipo As String
    Public Property idCampaniaMailchimp As String
    Public Property codNacionales As String

End Class
