'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class estetica
    Public Property cod As Long
    Public Property servicio As String
    Public Property fecha As Nullable(Of Date)
    Public Property paciente As String
    Public Property idTrabajador As Nullable(Of Long)
    Public Property fechaTrabajador As Nullable(Of Date)

End Class
