'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class examen_visual_optometrico
    Public Property id As Long
    Public Property fecha As Nullable(Of Date)
    Public Property edad As String
    Public Property curso As String
    Public Property escuela As String
    Public Property profesion As String
    Public Property telefono As String
    Public Property email As String
    Public Property examinador As String
    Public Property idCliente As Nullable(Of Long)
    Public Property revisionRutinaria As String
    Public Property remisOftalmologo As String
    Public Property dolorCabeza As String
    Public Property dolorOjos As String
    Public Property ojosRojos As String
    Public Property lagrimeo As String
    Public Property fotofobia As String
    Public Property visionBorrosa As String
    Public Property diplopia As String
    Public Property desviacionOjo As String
    Public Property perdidaCampo As String
    Public Property traumatismoCabezaOjo As String
    Public Property mareos As String
    Public Property perdidadConcentracion As String
    Public Property problemasAprendizaje As String
    Public Property otrosMotivoConsulta As String
    Public Property gafasLc As String
    Public Property cirugia As String
    Public Property estrabismo As String
    Public Property ambliopia As String
    Public Property cataratas As String
    Public Property glaucoma As String
    Public Property alteracionColores As String
    Public Property desprendimiento As String
    Public Property trauma As String
    Public Property diabetes As String
    Public Property hipertension As String
    Public Property arterioesclerosis As String
    Public Property tiroides As String
    Public Property otrosMotivosHisMed As String
    Public Property miopiaMagnaAntecedente As String
    Public Property hipermetropiaAntecedente As String
    Public Property astigmatismoAntecedente As String
    Public Property estrabismoAntecedente As String
    Public Property ambliopiaAntecedente As String
    Public Property glaucomaAntecedente As String
    Public Property alteracionColoresAntecedente As String
    Public Property patologiasRetinaAntecedente As String
    Public Property diabetesAntecedente As String
    Public Property hipertensionAntecedente As String
    Public Property tiroidesAntecedente As String
    Public Property otrosMotivosAntecedente As String
    Public Property antihistaminicosFarmacos As String
    Public Property antidepresivosFarmacos As String
    Public Property anticonceptivosFarmacos As String
    Public Property otrosFarmacos As String
    Public Property od1sincc As Nullable(Of Single)
    Public Property od2sincc As Nullable(Of Single)
    Public Property oi1sincc As Nullable(Of Single)
    Public Property oi2sincc As Nullable(Of Single)
    Public Property bino1sincc As Nullable(Of Single)
    Public Property bino2sincc As Nullable(Of Single)
    Public Property od1compensacion As Nullable(Of Single)
    Public Property od2compensacion As Nullable(Of Single)
    Public Property od3compensacion As Nullable(Of Single)
    Public Property oi1compensacion As Nullable(Of Single)
    Public Property oi2compensacion As Nullable(Of Single)
    Public Property oi3compensacion As Nullable(Of Single)
    Public Property adiccompensacion As Nullable(Of Single)
    Public Property od1concc As Nullable(Of Single)
    Public Property oi1concc As Nullable(Of Single)
    Public Property binoconcc As Nullable(Of Single)
    Public Property dnpod1 As Nullable(Of Single)
    Public Property dnpoi1 As Nullable(Of Single)
    Public Property dip1 As Nullable(Of Single)
    Public Property od1queratometria As Nullable(Of Single)
    Public Property oi1queratometria As Nullable(Of Single)
    Public Property od1retinoscopia As Nullable(Of Single)
    Public Property od2retinoscopia As Nullable(Of Single)
    Public Property oi1retinoscopia As Nullable(Of Single)
    Public Property oi2retinoscopia As Nullable(Of Single)
    Public Property od1refraccion As Nullable(Of Single)
    Public Property od2refraccion As Nullable(Of Single)
    Public Property oi1refraccion As Nullable(Of Single)
    Public Property oi2refraccion As Nullable(Of Single)
    Public Property od1equilibrio As Nullable(Of Single)
    Public Property od2equilibrio As Nullable(Of Single)
    Public Property oi1equilibrio As Nullable(Of Single)
    Public Property oi2equilibrio As Nullable(Of Single)
    Public Property od1adicionccf As Nullable(Of Single)
    Public Property od2adicionccf As Nullable(Of Single)
    Public Property od3adicionccf As Nullable(Of Single)
    Public Property oi1adicionccf As Nullable(Of Single)
    Public Property oi2adicionccf As Nullable(Of Single)
    Public Property oi3adicionccf As Nullable(Of Single)
    Public Property od1adiciontanteo As Nullable(Of Single)
    Public Property od2adiciontanteo As Nullable(Of Single)
    Public Property od3adiciontanteo As Nullable(Of Single)
    Public Property oi1adiciontanteo As Nullable(Of Single)
    Public Property oi2adiciontanteo As Nullable(Of Single)
    Public Property oi3adiciontanteo As Nullable(Of Single)
    Public Property od1distancia As Nullable(Of Single)
    Public Property oi1distancia As Nullable(Of Single)
    Public Property vl1alineamiento As Nullable(Of Single)
    Public Property vp1alineamiento As Nullable(Of Single)
    Public Property od1amplitud As Nullable(Of Single)
    Public Property od2amplitud As Nullable(Of Single)
    Public Property oi1amplitud As Nullable(Of Single)
    Public Property oi2amplitud As Nullable(Of Single)
    Public Property odoi1flexibilidad As Nullable(Of Single)
    Public Property odoi2flexibilidad As Nullable(Of Single)
    Public Property bino1flexibilidad As Nullable(Of Single)
    Public Property od1gafas As Nullable(Of Single)
    Public Property od2gafas As Nullable(Of Single)
    Public Property od3gafas As Nullable(Of Single)
    Public Property od4gafas As Nullable(Of Single)
    Public Property od5gafas As Nullable(Of Single)
    Public Property od6gafas As Nullable(Of Single)
    Public Property oi1gafas As Nullable(Of Single)
    Public Property oi2gafas As Nullable(Of Single)
    Public Property oi3gafas As Nullable(Of Single)
    Public Property oi4gafas As Nullable(Of Single)
    Public Property oi5gafas As Nullable(Of Single)
    Public Property oi6gafas As Nullable(Of Single)
    Public Property adic1gafas As Nullable(Of Single)
    Public Property od1lentes As Nullable(Of Single)
    Public Property od2lentes As Nullable(Of Single)
    Public Property od3lentes As Nullable(Of Single)
    Public Property od4lentes As Nullable(Of Single)
    Public Property od5lentes As Nullable(Of Single)
    Public Property od6lentes As Nullable(Of Single)
    Public Property oi1lentes As Nullable(Of Single)
    Public Property oi2lentes As Nullable(Of Single)
    Public Property oi3lentes As Nullable(Of Single)
    Public Property oi4lentes As Nullable(Of Single)
    Public Property oi5lentes As Nullable(Of Single)
    Public Property oi6lentes As Nullable(Of Single)
    Public Property adic1lentes As Nullable(Of Single)
    Public Property idTrabajador As Nullable(Of Long)
    Public Property fechaExamenRealizado As Nullable(Of Date)
    Public Property fechaTrabajador As Nullable(Of Date)

End Class
