'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class examen_capilar
    Public Property id As Long
    Public Property examen As String
    Public Property fechaGrabacion As Nullable(Of Date)
    Public Property recomendaciones As String
    Public Property idCliente As Nullable(Of Long)
    Public Property textura As String
    Public Property flexibilidad As String
    Public Property irrigacion As String
    Public Property seboHidratacion As String
    Public Property estado As String
    Public Property sintomas As String
    Public Property caspa1 As String
    Public Property caspa2 As String
    Public Property caspa3 As String
    Public Property caspa4 As String
    Public Property alopecia1 As String
    Public Property alopecia2 As String
    Public Property alopecia3 As String
    Public Property observacionesAlopecia As String
    Public Property fichero As String
    Public Property idTrabajador As Nullable(Of Long)
    Public Property fechaTrabajador As Nullable(Of Date)

End Class
