'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class faltas
    Public Property cod As Long
    Public Property idPedido As Nullable(Of Long)
    Public Property idLinea As Nullable(Of Long)
    Public Property cod_nacional As Nullable(Of Long)
    Public Property descripcion As String
    Public Property familia As String
    Public Property superFamilia As String
    Public Property cantidadPedida As Nullable(Of Integer)
    Public Property fechaFalta As Nullable(Of Date)
    Public Property cod_laboratorio As String
    Public Property laboratorio As String
    Public Property proveedor As String
    Public Property fechaPedido As Nullable(Of Date)
    Public Property pvp As Nullable(Of Single)
    Public Property puc As Nullable(Of Single)
    Public Property sistema As String
    Public Property categoria As String
    Public Property subcategoria As String
    Public Property superFamiliaAux As String
    Public Property familiaAux As String
    Public Property cambioClasificacion As Nullable(Of Boolean)

End Class
