'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class fechasconsultadas
    Public Property id As Long
    Public Property usuarioId As Nullable(Of Integer)
    Public Property fechaInicio As Nullable(Of Date)
    Public Property fechaFin As Nullable(Of Date)
    Public Property filtradoPor As String
    Public Property valorFiltrado As String
    Public Property fechaConsulta As Nullable(Of Date)

End Class
