'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class historia_tab
    Public Property id As Long
    Public Property idCliente As Nullable(Of Long)
    Public Property cigarrosUltimoMes As String
    Public Property cigarrosVida As String
    Public Property inicioConsumo As String
    Public Property intentosPrevios As String
    Public Property ultimoIntento As String
    Public Property abstinencia As String
    Public Property tratamiento As String
    Public Property idTrabajador As Nullable(Of Long)
    Public Property fechaTrabajador As Nullable(Of Date)

End Class
