'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class historia_farmacoterapeutica_tab
    Public Property id As Long
    Public Property idCliente As Nullable(Of Long)
    Public Property htaAntecedentes As String
    Public Property colesterolAntecedentes As String
    Public Property dmAntecedentes As String
    Public Property neoplasiasAntecedentes As String
    Public Property cardiopatiasAntecedentes As String
    Public Property respiratoriasAntecedentes As String
    Public Property depresionAntecedentes As String
    Public Property epilepsiasAntecedentes As String
    Public Property alcohoAntecedentes As String
    Public Property haTenidoEnfermedad As String
    Public Property haTenidoEnfermedadResp As String
    Public Property haTenidoEnfermedadCardio As String
    Public Property haTenidoEnfermedadDig As String
    Public Property haTenidoEnfermedadEnd As String
    Public Property haTenidoEnfermedadMus As String
    Public Property haTenidoEnfermedadPiel As String
    Public Property haTenidoEnfermedadRenal As String
    Public Property haTenidoEnfermedadNerv As String
    Public Property haTenidoEnfermedadPsi As String
    Public Property haEstadoIngresado As String
    Public Property numIngresos As Nullable(Of Integer)
    Public Property actualidadEnfermedad As String
    Public Property actualidadEnfermedadResp As String
    Public Property actualidadEnfermedadCardio As String
    Public Property actualidadEnfermedadDig As String
    Public Property actualidadEnfermedadEnd As String
    Public Property actualidadEnfermedadMus As String
    Public Property actualidadEnfermedadPiel As String
    Public Property actualidadEnfermedadRenal As String
    Public Property actualidadEnfermedadNerv As String
    Public Property actualidadEnfermedadPsi As String
    Public Property estaEmbarazada As String
    Public Property intervencionQuirurjica As String
    Public Property numIntervenciones As Nullable(Of Integer)
    Public Property alergias As String
    Public Property alergiasMedicamentos As String
    Public Property alergiasMedicamentosEspecifique As String
    Public Property alergiasComidas As String
    Public Property alergiasComidasEspecifique As String
    Public Property digestivos As String
    Public Property digestivosTratamiento As String
    Public Property apnea As String
    Public Property apneaTratamiento As String
    Public Property idTrabajador As Nullable(Of Long)
    Public Property fechaTrabajador As Nullable(Of Date)

End Class
