'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class homeopatia
    Public Property cod As Long
    Public Property homeopatia1 As String
    Public Property fecha_entrada As Nullable(Of Date)
    Public Property fecha_recogida As Nullable(Of Date)
    Public Property fecha_llegada As Nullable(Of Date)
    Public Property email As String
    Public Property telefono As String
    Public Property realizado As Nullable(Of Boolean)
    Public Property avisado As Nullable(Of Boolean)
    Public Property recogido As Nullable(Of Boolean)
    Public Property fechaRealizado As Nullable(Of Date)
    Public Property fechaAvisado As Nullable(Of Date)
    Public Property fechaRecogido As Nullable(Of Date)
    Public Property paciente As String
    Public Property proveedor As String
    Public Property otroProveedor As String
    Public Property idTrabajador As Nullable(Of Long)
    Public Property fechaTrabajador As Nullable(Of Date)

End Class
