'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class informes_mensuales_backup_16122016
    Public Property id As Decimal
    Public Property fechaCreacion As Nullable(Of Date)
    Public Property fechaModificacion As Nullable(Of Date)
    Public Property anio As Nullable(Of Long)
    Public Property mes As String
    Public Property dia As Nullable(Of Integer)
    Public Property trimestral As Nullable(Of Boolean)
    Public Property datosClientes As String
    Public Property observacionesAcciones As String
    Public Property mejoras_consejos As String
    Public Property observaciones As String
    Public Property eliminado As Nullable(Of Boolean)
    Public Property fechaEliminado As Nullable(Of Date)
    Public Property hash As String
    Public Property fechaHash As Nullable(Of Date)
    Public Property visto As Nullable(Of Integer)
    Public Property emailEnviado As Nullable(Of Boolean)

End Class
