'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class intervencion_basal_taq
    Public Property id As Long
    Public Property idCliente As Nullable(Of Long)
    Public Property fecha As Nullable(Of Date)
    Public Property tratamientoPropuesto As String
    Public Property derivaMedico As String
    Public Property autoayuda As String
    Public Property intruye As String
    Public Property idTrabajador As Nullable(Of Long)
    Public Property fechaTrabajador As Nullable(Of Date)

End Class
