'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class lin_pedidos
    Public Property linea As Decimal
    Public Property pedido As Integer
    Public Property codigo As Long
    Public Property cant_ped As Short
    Public Property cant_ser As Short
    Public Property num_vale As String
    Public Property pvp As Nullable(Of Single)
    Public Property iva As Nullable(Of Single)
    Public Property importeBruto As Nullable(Of Single)
    Public Property importeIva As Nullable(Of Single)
    Public Property importeNeto As Nullable(Of Single)
    Public Property lote As String
    Public Property eliminado As Nullable(Of Boolean)
    Public Property fechaEliminado As Nullable(Of Date)

End Class
