'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class lineas_campanias
    Public Property id As Decimal
    Public Property fecha As Nullable(Of Date)
    Public Property campaniaId As Nullable(Of Long)
    Public Property nombre As String
    Public Property importe As Nullable(Of Single)
    Public Property observaciones As String
    Public Property eliminado As Nullable(Of Boolean)
    Public Property fechaEliminado As Nullable(Of Date)

End Class
