'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class lineas_objetivo_unidades
    Public Property id As Decimal
    Public Property objetivoId As Nullable(Of Long)
    Public Property tipoAsociado As String
    Public Property asociado As String
    Public Property incremento As Nullable(Of Single)
    Public Property eliminado As Nullable(Of Boolean)
    Public Property fechaEliminado As Nullable(Of Date)
    Public Property orden As Nullable(Of SByte)

End Class
