'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class lineas_promociones
    Public Property id As Long
    Public Property codNacional As String
    Public Property referencia As String
    Public Property unidadesOrigen As Nullable(Of Integer)
    Public Property pvl As Nullable(Of Single)
    Public Property descuento As Nullable(Of Single)
    Public Property pvneto As Nullable(Of Single)
    Public Property pvpRecomendado As Nullable(Of Single)
    Public Property apartado As String
    Public Property promocionId As Nullable(Of Long)
    Public Property fichero As String
    Public Property eliminado As Nullable(Of Boolean)
    Public Property fechaEliminado As Nullable(Of Date)

End Class
