'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class lineas_incentivos_objetivo_unidades
    Public Property id As Decimal
    Public Property incentivoId As Nullable(Of Long)
    Public Property lineaIncentivoId As Nullable(Of Long)
    Public Property objetivoId As Nullable(Of Long)
    Public Property lineaObjetivoId As Nullable(Of Long)
    Public Property incrementoConseguir As Nullable(Of Single)
    Public Property eliminado As Nullable(Of Boolean)
    Public Property fechaEliminado As Nullable(Of Date)

End Class
