'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class lineas_objetivo_cualitativo
    Public Property id As Decimal
    Public Property objetivoId As Nullable(Of Long)
    Public Property descripcion As String
    Public Property valorIndicativo As Nullable(Of Single)
    Public Property importeConseguir As Nullable(Of Single)
    Public Property grupo As Nullable(Of Boolean)
    Public Property individual As Nullable(Of Boolean)
    Public Property valorIndicativoTotal As Nullable(Of Single)
    Public Property importeConseguirTotal As Nullable(Of Single)
    Public Property numTrabajadores As Nullable(Of Integer)
    Public Property eliminado As Nullable(Of Boolean)
    Public Property fechaEliminado As Nullable(Of Date)
    Public Property orden As Nullable(Of SByte)

End Class
