'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class medicamentos
    Public Property cod_barras As String
    Public Property cod_nacional As Long
    Public Property nombre As String
    Public Property superFamilia As String
    Public Property familia As String
    Public Property precio As Single
    Public Property descripcion As String
    Public Property laboratorio As String
    Public Property nombre_laboratorio As String
    Public Property proveedor As String
    Public Property pvpSinIva As Nullable(Of Single)
    Public Property iva As Nullable(Of Integer)
    Public Property stock As Nullable(Of Integer)
    Public Property puc As Nullable(Of Single)
    Public Property stockMinimo As Nullable(Of Integer)
    Public Property stockMaximo As Nullable(Of Integer)
    Public Property categoria As String
    Public Property subcategoria As String
    Public Property web As Nullable(Of Boolean)
    Public Property ubicacion As String
    Public Property presentacion As String
    Public Property descripcionTienda As String
    Public Property prestashopIdPS As Nullable(Of Integer)
    Public Property cargadoPS As Nullable(Of Boolean)
    Public Property fechaCargadoPS As Nullable(Of Date)
    Public Property activoPrestashop As Nullable(Of Boolean)
    Public Property actualizadoPS As Nullable(Of Boolean)
    Public Property eliminado As Nullable(Of Boolean)
    Public Property fechaEliminado As Nullable(Of Date)
    Public Property familiaAux As String
    Public Property fechaCaducidad As Nullable(Of Date)
    Public Property porDondeVoy As Nullable(Of Boolean)
    Public Property porDondeVoySinStock As Nullable(Of Boolean)
    Public Property fechaUltimaCompra As Nullable(Of Date)
    Public Property fechaUltimaVenta As Nullable(Of Date)
    Public Property baja As Nullable(Of Boolean)

End Class
