'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class mensajes_internos
    Public Property id As Decimal
    Public Property fechaCreacion As Nullable(Of Date)
    Public Property trabajadorId As Nullable(Of Long)
    Public Property asunto As String
    Public Property mensaje As String
    Public Property visto As Nullable(Of Boolean)
    Public Property leido As Nullable(Of Boolean)
    Public Property fechaVisto As Nullable(Of Date)
    Public Property fechaLeido As Nullable(Of Date)
    Public Property eliminado As Nullable(Of Boolean)
    Public Property fechaEliminado As Nullable(Of Date)

End Class
