'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class mensajes_servicios_clientes
    Public Property id As Long
    Public Property idServicioCliente As Long
    Public Property titulo As String
    Public Property descripcion As String
    Public Property hora As Nullable(Of System.TimeSpan)
    Public Property dias As String
    Public Property eliminado As Nullable(Of Boolean)
    Public Property fechaEliminado As Nullable(Of Date)
    Public Property emailFarmacia As String

End Class
