'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class nivel
    Public Property cod As Long
    Public Property nivel1 As Decimal
    Public Property nivel2 As Decimal
    Public Property nivel3 As Decimal
    Public Property nivel4 As Decimal
    Public Property intervalo As Nullable(Of Integer)

End Class
