'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class nombres_bebes
    Public Property idNombreBebe As Decimal
    Public Property nombreBebe As String
    Public Property fechaNacimiento As Nullable(Of Date)
    Public Property paciente As String
    Public Property eliminado As Nullable(Of Boolean)

End Class
