'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class notificaciones_push_enviadas
    Public Property id As Decimal
    Public Property fecha As Nullable(Of Date)
    Public Property titulo As String
    Public Property mensaje As String
    Public Property mensajeLargo As String
    Public Property url As String
    Public Property tipo As String
    Public Property idExterno As Nullable(Of Long)
    Public Property hash As String
    Public Property visto As Nullable(Of Boolean)
    Public Property fechaVisto As Nullable(Of Date)

End Class
