'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class numero
    Public Property cod As Long
    Public Property numero1 As Long
    Public Property marcado As String
    Public Property fecha As Integer
    Public Property hora As Integer
    Public Property hora_atencion As Integer
    Public Property foto As String
    Public Property mostrador As Integer
    Public Property fecha_marcado As Long
    Public Property tipo As String

End Class
