'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class objetivo_listado_medicamentos
    Public Property id As Decimal
    Public Property lineaObjetivoId As Nullable(Of Long)
    Public Property cod_nacional As Nullable(Of Long)
    Public Property descripcion As String
    Public Property unidadesC As Nullable(Of Integer)
    Public Property pvpC As Nullable(Of Single)
    Public Property pucC As Nullable(Of Single)
    Public Property importeC As Nullable(Of Single)
    Public Property unidadesV As Nullable(Of Integer)
    Public Property pvpV As Nullable(Of Single)
    Public Property pucV As Nullable(Of Single)
    Public Property importeV As Nullable(Of Single)

End Class
