'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class objetivos
    Public Property id As Decimal
    Public Property fechaCreacion As Nullable(Of Date)
    Public Property fechaModificacion As Nullable(Of Date)
    Public Property activo As Nullable(Of Boolean)
    Public Property descripcion As String
    Public Property fechaInicio As Nullable(Of Date)
    Public Property fechaFin As Nullable(Of Date)
    Public Property fechaInicioCompara As Nullable(Of Date)
    Public Property fechaFinCompara As Nullable(Of Date)
    Public Property ticketMedio As Nullable(Of Boolean)
    Public Property incrementoPorcentaje As Nullable(Of Single)
    Public Property incrementoImporte As Nullable(Of Single)
    Public Property importeComparar As Nullable(Of Single)
    Public Property importeVirtual As Nullable(Of Single)
    Public Property observaciones As String
    Public Property eliminado As Nullable(Of Boolean)
    Public Property fechaEliminado As Nullable(Of Date)

End Class
