'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class objetivos_varios
    Public Property id As Decimal
    Public Property fechaCreacion As Nullable(Of Date)
    Public Property fechaModificacion As Nullable(Of Date)
    Public Property activo As Nullable(Of Boolean)
    Public Property descripcion As String
    Public Property fechaInicio As Nullable(Of Date)
    Public Property fechaFin As Nullable(Of Date)
    Public Property tipoObjetivo As String
    Public Property aplicadoA As String
    Public Property valorObjetivo As Nullable(Of Single)
    Public Property observaciones As String
    Public Property importeIncentivo As Nullable(Of Single)
    Public Property incentivoGrupal As Nullable(Of Boolean)
    Public Property eliminado As Nullable(Of Boolean)
    Public Property fechaEliminado As Nullable(Of Date)

End Class
