'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class pedidos_express
    Public Property id As Long
    Public Property nombre As String
    Public Property telefono As String
    Public Property email As String
    Public Property pedido As String
    Public Property preparado As Nullable(Of Boolean)
    Public Property fechaPedido As Nullable(Of Date)
    Public Property fechaPreparado As Nullable(Of Date)
    Public Property fechaRecogida As Nullable(Of Date)
    Public Property recogido As Nullable(Of Boolean)
    Public Property eliminado As Nullable(Of Boolean)
    Public Property fechaEliminado As Nullable(Of Date)
    Public Property notificado As Nullable(Of Boolean)

End Class
