'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class pedidos
    Public Property id As Decimal
    Public Property idPedido As Nullable(Of Long)
    Public Property fechaPedido As Nullable(Of Date)
    Public Property hora As Nullable(Of Date)
    Public Property numLineas As Nullable(Of Integer)
    Public Property importePvp As Nullable(Of Single)
    Public Property importePuc As Nullable(Of Single)
    Public Property idProveedor As String
    Public Property proveedor As String
    Public Property trabajador As String
    Public Property sistema As String

End Class
