'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class pendiente_puntos_old
    Public Property cod As Long
    Public Property idventa As Long
    Public Property idnlinea As Long
    Public Property cod_barras As String
    Public Property cod_nacional As Long
    Public Property descripcion As String
    Public Property familia As String
    Public Property cantidad As Integer
    Public Property precio As Decimal
    Public Property tipoPago As Nullable(Of Integer)
    Public Property fecha As Integer
    Public Property dni As String
    Public Property cargado As String
    Public Property hora As Date
    Public Property cruzados As String
    Public Property puesto As String
    Public Property trabajador As String
    Public Property cod_laboratorio As String
    Public Property laboratorio As String
    Public Property receta As String
    Public Property fechaVenta As Nullable(Of Date)
    Public Property superFamilia As String
    Public Property pvp As Nullable(Of Single)
    Public Property puc As Nullable(Of Single)
    Public Property categoria As String
    Public Property subcategoria As String
    Public Property sistema As String
    Public Property puntos As Nullable(Of Single)
    Public Property dtoLinea As Nullable(Of Single)
    Public Property dtoVenta As Nullable(Of Single)
    Public Property superFamiliaAux As String
    Public Property familiaAux As String
    Public Property cambioClasificacion As Nullable(Of Boolean)

End Class
