'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class personas_reservas
    Public Property id_persona As Long
    Public Property nombre As String
    Public Property apellidos As String
    Public Property email As String
    Public Property telefono As String
    Public Property horaInicio As Nullable(Of System.TimeSpan)
    Public Property horaFin As Nullable(Of System.TimeSpan)
    Public Property codCliente As Nullable(Of Long)

End Class
