'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class plano_farmacia
    Public Property cod As Long
    Public Property unox As Decimal
    Public Property unoy As Decimal
    Public Property dosx As Decimal
    Public Property dosy As Decimal
    Public Property tresx As Decimal
    Public Property tresy As Decimal
    Public Property cuatrox As Decimal
    Public Property cuatroy As Decimal
    Public Property cincox As Decimal
    Public Property cincoy As Decimal
    Public Property seisx As Decimal
    Public Property seisy As Decimal
    Public Property sietex As Decimal
    Public Property sietey As Decimal

End Class
