'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class posologia
    Public Property cod As Long
    Public Property cod_nacional As Nullable(Of Long)
    Public Property medicamento As String
    Public Property hora As Nullable(Of System.TimeSpan)
    Public Property fecha_inicio As Nullable(Of Date)
    Public Property fecha_fin As Nullable(Of Date)
    Public Property frecuencia As String
    Public Property paciente As String

End Class
