'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class programacion_sincronizador
    Public Property id As Long
    Public Property estado As String
    Public Property horaM As Nullable(Of System.TimeSpan)
    Public Property horaT As Nullable(Of System.TimeSpan)
    Public Property activo As Nullable(Of Boolean)

End Class
