'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class promociones
    Public Property id As Long
    Public Property fechaCreacion As Nullable(Of Date)
    Public Property fechaInicio As Nullable(Of Date)
    Public Property fechaFin As Nullable(Of Date)
    Public Property descripcion As String
    Public Property observaciones As String
    Public Property tipo As String
    Public Property emailsPedidos As String
    Public Property eliminado As Nullable(Of Boolean)
    Public Property fechaEliminado As Nullable(Of Date)
    Public Property fechaModificacion As Nullable(Of Date)

End Class
