'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class protocolos
    Public Property id As Long
    Public Property titulo As String
    Public Property idTrabajador As Nullable(Of Long)
    Public Property actividad As String
    Public Property actividadExpandida As String
    Public Property fechaInicio As Nullable(Of Date)
    Public Property fechaFin As Nullable(Of Date)
    Public Property hora As String
    Public Property dias As String
    Public Property emailFarmacia As String
    Public Property activo As Nullable(Of Boolean)
    Public Property eliminado As Nullable(Of Boolean)
    Public Property fechaEliminado As Nullable(Of Date)
    Public Property periocidad As String
    Public Property fechaConcreta As Nullable(Of Date)

End Class
