'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class protocolos_tramos
    Public Property id As Long
    Public Property idProtocolo As Nullable(Of Long)
    Public Property fecha As Nullable(Of Date)
    Public Property realizado As Nullable(Of Boolean)
    Public Property fechaRealizado As Nullable(Of Date)
    Public Property idTrabajador As Nullable(Of Long)

End Class
