'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ps_categorias
    Public Property id As Decimal
    Public Property categoria As String
    Public Property padre As String
    Public Property prestashopPadreId As Nullable(Of Integer)
    Public Property prestashopId As Nullable(Of Integer)
    Public Property cargadoPS As Nullable(Of Boolean)
    Public Property activoPrestashop As Nullable(Of Boolean)
    Public Property activoPadrePrestashop As Nullable(Of Boolean)

End Class
