'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ps_laboratorios
    Public Property id As Decimal
    Public Property cod_laboratorio As String
    Public Property laboratorio As String
    Public Property prestashopId As Nullable(Of Integer)
    Public Property cargadoPS As Nullable(Of Boolean)
    Public Property prestashopIdMF As Nullable(Of Integer)
    Public Property cargadoPSMF As Nullable(Of Boolean)

End Class
