'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ps_log
    Public Property id As Decimal
    Public Property fecha As Nullable(Of Date)
    Public Property cod_nacional As Nullable(Of Long)
    Public Property [class] As String
    Public Property action As String
    Public Property field As String
    Public Property old_value As String
    Public Property new_value As String
    Public Property value As String
    Public Property notes As String

End Class
