'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ps_movimientos_stock
    Public Property id As Decimal
    Public Property prestashopId As Nullable(Of Integer)
    Public Property cod_nacional As Nullable(Of Long)
    Public Property cantidad As Nullable(Of Integer)
    Public Property fecha As Nullable(Of Date)
    Public Property tipo_stock As String
    Public Property procesado As Nullable(Of Boolean)
    Public Property fechaProcesado As Nullable(Of Date)

End Class
