'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ps_rel_imagenes
    Public Property productoId As Decimal
    Public Property imagenId As Decimal
    Public Property orden As Nullable(Of Integer)
    Public Property portada As Nullable(Of Boolean)

End Class
