'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class publicidad
    Public Property cod As Integer
    Public Property titulo_antes As String
    Public Property titulo_despues As Decimal
    Public Property foto_antes As String
    Public Property foto_despues As String
    Public Property descripcion As String
    Public Property peso As Decimal
    Public Property cod_familia As Long
    Public Property orden As Integer

End Class
