'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class rango_importes_colores
    Public Property id As Decimal
    Public Property activo As Nullable(Of Boolean)
    Public Property fecha As Nullable(Of Date)
    Public Property color As String
    Public Property importeMin As Nullable(Of Single)
    Public Property importeMax As Nullable(Of Single)
    Public Property descripcion As String
    Public Property meses As String
    Public Property eliminado As Nullable(Of Boolean)
    Public Property fechaEliminado As Nullable(Of Date)

End Class
