'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ranking
    Public Property id As Decimal
    Public Property anio As Nullable(Of Long)
    Public Property mes As String
    Public Property dia As Nullable(Of Integer)
    Public Property trimestral As Nullable(Of Boolean)
    Public Property anual As Nullable(Of Boolean)
    Public Property datosTrabajadores As String

End Class
