'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class recomendaciones_cruzadas
    Public Property id As Long
    Public Property idVentaCruzada As Nullable(Of Long)
    Public Property tipoRecomendado As String
    Public Property recomendacion As String

End Class
