'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class regalos
    Public Property cod_barras As String
    Public Property nombre As String
    Public Property puntos As Single
    Public Property precio As Single
    Public Property descripcion As String
    Public Property medicamento As String

End Class
