'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class reproducciones
    Public Property id As Decimal
    Public Property tipo As String
    Public Property formato As String
    Public Property tamanio As String
    Public Property fichero As String
    Public Property mostrador As String

End Class
