'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class respuestas_usuarios
    Public Property id As Long
    Public Property idEncuesta As Nullable(Of Long)
    Public Property idPregunta As Nullable(Of Long)
    Public Property idRespuesta As Nullable(Of Long)
    Public Property respuesta As String
    Public Property email As String
    Public Property ip As String
    Public Property provincia As Nullable(Of Integer)

End Class
