'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class respuestas
    Public Property id As Long
    Public Property tituloRespuesta As String
    Public Property idPregunta As Nullable(Of Long)
    Public Property eliminado As Nullable(Of Boolean)
    Public Property fechaEliminado As Nullable(Of Date)

End Class
