'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class seguimiento_embarazo_copy
    Public Property id As Decimal
    Public Property fecha As Nullable(Of Date)
    Public Property estado As String
    Public Property idPeriodo As Nullable(Of Long)
    Public Property consejo As String
    Public Property imagen As String
    Public Property eliminado As Nullable(Of Boolean)
    Public Property fechaEliminado As Nullable(Of Date)

End Class
