'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class servicios_clientes_suscritos
    Public Property id As Long
    Public Property idServicioCliente As Nullable(Of Long)
    Public Property idCliente As Nullable(Of Long)

End Class
