'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class servicios_citas_tramos_copy
    Public Property id As Long
    Public Property servicioId As Nullable(Of Long)
    Public Property fecha As Nullable(Of Date)
    Public Property horaInicio As Nullable(Of System.TimeSpan)
    Public Property horaFin As Nullable(Of System.TimeSpan)
    Public Property personasMax As Nullable(Of Integer)
    Public Property activo As Nullable(Of Boolean)
    Public Property reservas As Nullable(Of Integer)
    Public Property servicioCruzado As String

End Class
