'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class servicios_citas_dias_copy
    Public Property id As Decimal
    Public Property servicioId As Nullable(Of Long)
    Public Property dia As String
    Public Property horaInicioM As Nullable(Of System.TimeSpan)
    Public Property horaFinM As Nullable(Of System.TimeSpan)
    Public Property horaInicioT As Nullable(Of System.TimeSpan)
    Public Property horaFinT As Nullable(Of System.TimeSpan)

End Class
