'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class sms_enviados
    Public Property cod As Long
    Public Property dni_tra As String
    Public Property nombre_tra As String
    Public Property dni As String
    Public Property nombre As String
    Public Property fecha As String
    Public Property texto As String

End Class
