'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class test_fagerstrom_tab
    Public Property id As Long
    Public Property idCliente As Nullable(Of Long)
    Public Property primerCigarro As String
    Public Property lugaresProhibidos As String
    Public Property desagrada As String
    Public Property cigarrosDia As String
    Public Property levantarse As String
    Public Property enfermo As String
    Public Property puntuacion As Nullable(Of Integer)
    Public Property cooximetria As String
    Public Property valorCooximetria As String
    Public Property motivosDejar As String
    Public Property idTrabajador As Nullable(Of Long)
    Public Property fechaTrabajador As Nullable(Of Date)

End Class
