'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class test_richmond_tab
    Public Property id As Long
    Public Property idCliente As Nullable(Of Long)
    Public Property dejarFacil As String
    Public Property dejar2sem As String
    Public Property interesDejarlo As String
    Public Property proximos6meses As String
    Public Property puntuacion As Nullable(Of Integer)
    Public Property idTrabajador As Nullable(Of Long)
    Public Property fechaTrabajador As Nullable(Of Date)

End Class
