'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tmp_entregas_clientes
    Public Property id As Decimal
    Public Property usuarioId As Nullable(Of Integer)
    Public Property idventa As Nullable(Of Long)
    Public Property idnlinea As Nullable(Of Long)
    Public Property codigo As String
    Public Property descripcion As String
    Public Property cantidad As Nullable(Of Integer)
    Public Property precio As Nullable(Of Single)
    Public Property pvp As Nullable(Of Single)
    Public Property tipo As String
    Public Property farmacia As String
    Public Property fechaEntrega As Nullable(Of Date)
    Public Property puesto As String
    Public Property sistema As String
    Public Property trabajador As String

End Class
