'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tmp_ventas
    Public Property id As Decimal
    Public Property usuarioId As Nullable(Of Integer)
    Public Property idventa As Nullable(Of Long)
    Public Property idlineaventa As Nullable(Of Long)
    Public Property cod_nacional As Nullable(Of Long)
    Public Property medicamento As String
    Public Property familia As String
    Public Property subfamilia As String
    Public Property tipoPago As String
    Public Property cantidad As Nullable(Of Integer)
    Public Property precioVenta As Nullable(Of Single)
    Public Property pvp As Nullable(Of Single)
    Public Property pCoste As Nullable(Of Single)
    Public Property farmacia As String
    Public Property cod_laboratorio As String
    Public Property laboratorio As String
    Public Property receta As String
    Public Property fechaVenta As Nullable(Of Date)
    Public Property puesto As String
    Public Property sistema As String
    Public Property trabajador As String
    Public Property dtoVenta As Nullable(Of Single)

End Class
