'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class trabajador
    Public Property id As Long
    Public Property nombre As String
    Public Property apellidos As String
    Public Property telefono As String
    Public Property email As String
    Public Property activo As Nullable(Of Boolean)
    Public Property tarjeta As String
    Public Property modificable As Nullable(Of Boolean)
    Public Property externo As Nullable(Of Boolean)
    Public Property visibleApp As Nullable(Of Boolean)
    Public Property visibleObjetivos As Nullable(Of Boolean)
    Public Property visibleEsfuerzos As Nullable(Of Boolean)
    Public Property visibleVentasCruzadas As Nullable(Of Boolean)

End Class
