'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class trabajadores_citas_tramos
    Public Property id As Long
    Public Property idTrabajador As Long
    Public Property idCitaTramo As Long
    Public Property fecha As Nullable(Of Date)
    Public Property idPersona As Nullable(Of Long)

End Class
