'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tricogramas_examen_capilar
    Public Property id As Long
    Public Property idExamenCapilar As Nullable(Of Long)
    Public Property ubicacion As String
    Public Property fecha As Nullable(Of Date)
    Public Property anagenos As String
    Public Property catagenos As String
    Public Property telogenos As String
    Public Property grasos As String
    Public Property intoxicados As String
    Public Property corroidos As String
    Public Property atrepsicos As String
    Public Property atrofiados As String
    Public Property anemicos As String
    Public Property queratinizados As String
    Public Property rotos As String

End Class
