'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class usuario_dashboard
    Public Property id As Decimal
    Public Property usuarioId As Nullable(Of Long)
    Public Property dashboardId As Nullable(Of Long)
    Public Property acceso As Nullable(Of Boolean)

End Class
