'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class usuarios
    Public Property id As Long
    Public Property nombre As String
    Public Property apellidos As String
    Public Property usuario As String
    Public Property clave As String
    Public Property email As String
    Public Property rolId As Nullable(Of Integer)
    Public Property fechaAlta As Nullable(Of Date)
    Public Property fechaBaja As Nullable(Of Date)
    Public Property ultimoAcceso As Nullable(Of Date)
    Public Property regenerandoVentas As Nullable(Of Boolean)

End Class
