'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class valores_indicativos_incentivos_cualitativos_individual
    Public Property id As Decimal
    Public Property lineaIncentivoId As Nullable(Of Long)
    Public Property objetivoId As Nullable(Of Long)
    Public Property lineaObjetivoId As Nullable(Of Long)
    Public Property descripcionObjetivo As String
    Public Property valorIndicativoConseguido As Nullable(Of Single)

End Class
