'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ventas_cruzadas
    Public Property id As Decimal
    Public Property activo As Nullable(Of Boolean)
    Public Property fechaCreacion As Nullable(Of Date)
    Public Property fechaModificacion As Nullable(Of Date)
    Public Property descripcion As String
    Public Property tipoVentaCruzada As String
    Public Property comision As Nullable(Of Single)
    Public Property tipoComision As String
    Public Property numVentasRealizar As Nullable(Of Integer)
    Public Property tipoObjetivo As String
    Public Property tipoVentaRecomendacion As String
    Public Property numCoincidencias As Nullable(Of Integer)
    Public Property tipoAsociado As String
    Public Property mensaje As String
    Public Property tipoMultimedia As String
    Public Property formato As String
    Public Property fichero As String
    Public Property eliminado As Nullable(Of Boolean)
    Public Property fechaEliminado As Nullable(Of Date)

End Class
