'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class wa_enviados
    Public Property id As Decimal
    Public Property fecha As Nullable(Of Date)
    Public Property dni As String
    Public Property nombre As String
    Public Property movil As String
    Public Property mensaje As String

End Class
