//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lector.Sharp.Wpf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class categorizacion
    {
        public long cod_nacional { get; set; }
        public string nombre { get; set; }
        public string familia { get; set; }
        public string subfamilia { get; set; }
        public string laboratorio { get; set; }
    }
}
