//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lector.Sharp.Wpf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicamentos
    {
        public string cod_barras { get; set; }
        public long cod_nacional { get; set; }
        public string nombre { get; set; }
        public string superFamilia { get; set; }
        public string familia { get; set; }
        public float precio { get; set; }
        public string descripcion { get; set; }
        public string laboratorio { get; set; }
        public string nombre_laboratorio { get; set; }
        public string proveedor { get; set; }
        public Nullable<float> pvpSinIva { get; set; }
        public Nullable<int> iva { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<float> puc { get; set; }
        public Nullable<int> stockMinimo { get; set; }
        public Nullable<int> stockMaximo { get; set; }
        public string categoria { get; set; }
        public string subcategoria { get; set; }
        public Nullable<bool> web { get; set; }
        public string ubicacion { get; set; }
        public string presentacion { get; set; }
        public string descripcionTienda { get; set; }
        public Nullable<int> prestashopIdPS { get; set; }
        public Nullable<bool> cargadoPS { get; set; }
        public Nullable<System.DateTime> fechaCargadoPS { get; set; }
        public Nullable<bool> activoPrestashop { get; set; }
        public Nullable<bool> actualizadoPS { get; set; }
        public Nullable<bool> eliminado { get; set; }
        public Nullable<System.DateTime> fechaEliminado { get; set; }
        public string familiaAux { get; set; }
        public Nullable<System.DateTime> fechaCaducidad { get; set; }
        public Nullable<bool> porDondeVoy { get; set; }
        public Nullable<bool> porDondeVoySinStock { get; set; }
        public Nullable<System.DateTime> fechaUltimaCompra { get; set; }
        public Nullable<System.DateTime> fechaUltimaVenta { get; set; }
        public Nullable<bool> baja { get; set; }
    }
}
