//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lector.Sharp.Wpf.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SisFarmaEntities : DbContext
    {
        public SisFarmaEntities()
            : base("name=SisFarmaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<medicamentos> medicamentos { get; set; }
        public virtual DbSet<sinonimos> sinonimos { get; set; }
        public virtual DbSet<trabajador> trabajador { get; set; }
        public virtual DbSet<asociados_cruzadas> asociados_cruzadas { get; set; }
        public virtual DbSet<ventas_cruzadas> ventas_cruzadas { get; set; }
        public virtual DbSet<listas_articulos> listas_articulos { get; set; }
        public virtual DbSet<categorizacion> categorizacion { get; set; }
    }
}
