//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lector.Sharp.Wpf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trabajador
    {
        public long id { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public Nullable<bool> activo { get; set; }
        public string tarjeta { get; set; }
        public Nullable<bool> modificable { get; set; }
        public Nullable<bool> externo { get; set; }
        public Nullable<bool> visibleApp { get; set; }
        public Nullable<bool> visibleObjetivos { get; set; }
        public Nullable<bool> visibleEsfuerzos { get; set; }
        public Nullable<bool> visibleVentasCruzadas { get; set; }
    }
}
