//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lector.Sharp.Wpf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventas_cruzadas
    {
        public decimal id { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public string descripcion { get; set; }
        public string tipoVentaCruzada { get; set; }
        public Nullable<float> comision { get; set; }
        public string tipoComision { get; set; }
        public Nullable<int> numVentasRealizar { get; set; }
        public string tipoObjetivo { get; set; }
        public string tipoVentaRecomendacion { get; set; }
        public Nullable<int> numCoincidencias { get; set; }
        public string tipoAsociado { get; set; }
        public string mensaje { get; set; }
        public string tipoMultimedia { get; set; }
        public string formato { get; set; }
        public string fichero { get; set; }
        public Nullable<bool> eliminado { get; set; }
        public Nullable<System.DateTime> fechaEliminado { get; set; }
    }
}
